### ISSUE TITLE
Manual Download: File type/structure

### ISSUE THREAD

**Issue by TheWeion** [ElDewrito/HaloShare#3]
The Manual Download feature is too complicated for the average user, the .map/.variant files should be packed in a zip file/auto extracting archive with the file structure of:
- For Maps: "mods\maps\MAPNAME\sandbox.map"
- For Variants: "mods\variants\VARNAME\variant.slayer" (Replace slayer file extension with correct Gametype)

**Comment by Wombarly** [comment]
That folder structure isn't required for loading the files. Just drop the `.bin` files in the proper folder (`mods\maps\` or `mods\variants\`) And the file will load in-game.
